### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by heruku** [dirv/pinaclj#5]
User should be able write and use their own themes for the site. Should there be a `theme` directory which includes the templates and the stylesheets/javascripts?

**Comment by heruku** [comment]
Links?

**Comment by dirv** [comment]
There is a new `-t` switch which allows the user to specify a template directory. The `post.html` template is now read from `/templates/post.html` from within that directory, rather than from a resource in the compiled jar.

Lots more work to be done here, but I'll thinking of three subdirectories in a theme:

`/templates` - Enlive HTML templates per page type, so posts use `post.html`. Authors might use `author.html`.
`/static` - These files are copied across as-is.
`/single` - Enlive HTML templates that represent a single page, e.g. `/index.html` and `/404.html`.
